name: CI

on:
  push:
    paths-ignore: ['**.md', 'art/**']
    branches:
    - main
  pull_request:
    paths-ignore: ['**.md', 'art/**']
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    env:
      ZIP_FILE_NAME: ${{ 'NetIRC.Desktop-${github.ref}.zip' }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5

    - name: Restore Packages
      run: nuget restore NetIRC.Desktop.sln

    - name: Build and Test
      run: ./Build.ps1
      shell: pwsh

    - name: Zip Files
      uses: vimtor/action-zip@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: artifacts/
        dest: ${{ env.ZIP_FILE_NAME }}

    - name: GH Release
      uses: softprops/action-gh-release@v0.1.5
      if: startsWith(github.ref, 'refs/tags/')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        body: Release
        name: Release ${{ github.ref }}
        draft: true
        files: ${{ env.ZIP_FILE_NAME }}

    - name: Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: artifacts
        path: artifacts/**
